### PR TITLE
Updated for 1.0

### PR DESCRIPTION
**Pull request by mlhetland**
Updated to use new iteration protocol, if available. Importing `done` creates problems otherwise.

### CODE REVIEW

**Comment by mpastell** [comment]
Any change for merging this and tagging a new release soon? It would be great to get `Weave.jl` running on 1.0 and it depends on this package.

**Comment by mlhetland** [comment]
It'd be great for me to have this work by the end of the week; otherwise, I'll be using 0.7 in my course this semester :-}

**Comment by sglyon** [comment]
Thank  you for submitting.

Will you please enable tests on julia 0.7 and 1.0? To do this we need to change [these lines](https://github.com/dcjones/YAML.jl/blob/b2f76eebfe40e9432b0465eee4b3da1a6d7de3b6/.travis.yml#L4-L6) to also include `- 0.7` and `- 1.0`

Once we see that this fix changes tests we will be good to merge.

**Comment by mlhetland** [comment]
It seems it's the test infrastructure itself that fails, as it uses `Pkg` in a pre-1.0 way?

**Comment by mlhetland** [comment]
That is, rather than `julia -e 'Pkg.clone(pwd())`, it should be `julia -e 'using Pkg; Pkg.clone(pwd())`, though only for Julia 1.0, so unless you can have different commands for different versions, I guess you need an `if VERSION` thing in there as well.

**Comment by mpastell** [comment]
@mlhetland yes, that's what some other packages seem to use.

**Comment by mlhetland** [comment]
Maybe something @sglyon wants to address? (Or should I change it? Not sure where the Travis infrastructure is, ATM, but I’m sure it’s possible to find it :-))

**Comment by sglyon** [comment]
I think we should make that change -- it is what I would do myself so if you are willing to do it on this branch that'd be great!

**Comment by mlhetland** [comment]
Didn't notice that it was all just further down in the Travis-file xD Fixed.

**Comment by mlhetland** [comment]
Hm. I thought I tested it with 1.0, but it seems maybe I only tested with 0.7 for deprecation warnings. Still importing `start` and `next`, which don't exist in 1.0. Sorry about that! I'll do some bug-fixing an test properly in 1.0 :-)

**Comment by mlhetland** [comment]
Well, one problem is that we'll need `Codecs#master`. I guess they haven't tagged a release with the fixes there yet.

**Comment by mpastell** [comment]
Codecs has been tagged, but not merged https://github.com/JuliaLang/METADATA.jl/pull/16489 .

**Comment by mlhetland** [comment]
Oh, OK.

**Comment by mlhetland** [comment]
Anyway: I've tested with Julia 0.6, 0.7 and 1.0, and the tests run fine locally for me. But then, of course, I use `Compat` for 0.6 and `Compat#master` for 0.7 and 1.0.

**Comment by mlhetland** [comment]
So I guess as soon as we get the right version of `Codecs`, the tests here should pass.

**Comment by sglyon** [comment]
Sounds great, thank you for all the work here. Please notify us on this thread when I should review and prepare to merge

**Comment by BenJWard** [comment]
What is the status of this PR please? We need a 1.0 compatible version of YAML for BioJulia packages ASAP, but don't want to tread on toes of people already working on PRs :)

**Comment by BenJWard** [comment]
Codecs.jl v0.5.0 has been release which works for julia v0.7 / v1.0, if this PR uses that version it should pass?

**Comment by mlhetland** [comment]
The holdup has been that Codecs 0.5 hasn't been merged into METADATA. If you can specify specific tags or branches in your requirements, you could always just use this PR and 0.5 of Codecs directly. I could add a tag, if that's useful (i.e., rather than checking out the branch). But using `Codecs#v0.5.0` and `https://github.com/mlhetland/YAML.jl#1.0-fixes` currently works.

As soon as Codecs 0.5 is in METADATA, the checks here should pass, I guess, yes.

**Comment by sglyon** [comment]
Ok great, thank you for the update

**Comment by mlhetland** [comment]
I’m on my phone right now, so it’s a bit awkward to check, but I believe `Codecs` 0.5 should now be available. Can we manually re-run the checks? (It seems they’re stale at the moment?)

**Comment by BenJWard** [comment]
@mlhetland Codec 0.5 is indeed available now. If you have access to the travis you re-run the CI checks.

**Comment by mlhetland** [comment]
Hm. If I do have access, I at least can’t figure out how. (Wouldn’t I need write access to this repo? Am I missing something?)

**Comment by mlhetland** [comment]
Just thought I'd push a change to trigger a new check – so I added a `Project.toml` file. :-)

**Comment by mlhetland** [comment]
Being too clever here, I guess – breaking stuff. (Tricky when I can't test the CI stuff locally…) The deprecation warning for `clone` said to use `add`, but that doesn't work with a path, it seems. (Maybe I'm just using it wrong.) And there was an issue with developing a package with the same UUID as the project (which I guess makes sense – though here it *is* the same project), so I just removed the `Project.toml` file, again. I think it's correct – it works fine with, say, `instantiate`; it's just that the Travis setup had issues with it. I guess it can be re-added later.

**Comment by mpastell** [comment]
See e.g Weave for travis config that works with project.toml https://github.com/mpastell/Weave.jl/blob/master/.travis.yml

**Comment by mlhetland** [comment]
Ah – yeah, I looked at Weave (since I assumed you were up to date, given the discussion earlier :-). I just didn't want to hack around too much, and wasn't sure which parts worked with Julia 0.6 (given that some parts of it don't). If you have a suggested edit for the YAML Travis file, I'd be happy to implement it :-)

**Comment by mlhetland** [comment]
I'm having a look at it now.

**Comment by mlhetland** [comment]
All done, and ready to merge! (cc @sglyon)

**Comment by mlhetland** [comment]
Now that `YAML.jl` is in BioJulia, maybe @BenJWard can merge this?

**Comment by sglyon** [comment]
Merged thank you!

**Comment by BenJWard** [comment]
Thanks for merging @sglyon

**Comment by mlhetland** [comment]
Now getting a release would be great, so this becomes available without using `YAML#master`… :-> (BTW, my `Project.toml` already says `version = 0.2.2`.)

**Comment by BenJWard** [comment]
I’m coming to this only now of course and I don’t know how the versioning has been done previously.
I tried to release a v0.2.1 in line with your Project.toml, but attobot yelled at me - the metadata url is still set to the old repo, so I’ve submitted a PR to fix that and then v0.2.2 can get released without a hitch.

Best,

Ben.

**Comment by BenJWard** [comment]
Actually the version number is going to be v0.3.0, since julia 0.5 support is dropped, and previous v0.2.x versions supported julia 0.5, METADATA CI is making me increment the minor version number (as it should to be fair!).

**Comment by mlhetland** [comment]
Ah, sure. You should edit `Project.toml` so it has `version = "3.0.0"`, then :-)

**Pull request merged**
