### PR TITLE
Drop support for Julia versions before 1.0.

### PR DESCRIPTION
**Pull request by GunnarFarneback**
* Drop support for Julia versions before 1.0.
* Remove Compat dependency.
* Update Project.toml to allow auto-merge to General registry.
* Update Travis configuration.
* Replace Codecs dependency with Base64 stdlib.
* Bump version to 0.4.0.

### CODE REVIEW

**Comment by kescobo** [comment]
Looks great, thanks for doing this! Only failure appears to be a minor loss of coverage, but I don't think that merits holding it up. I'm going to give until end of business today in the off chance anyone raises objections, then I'll merge this and do the manual tag mentioned in #73.

**Comment by GunnarFarneback** [comment]
> Only failure appears to be a minor loss of coverage,

That report is weird since it claims coverage changes in untouched files and that the total number of missed lines have increased despite a 100% coverage of the diff. But anyhow, if you make simplifications to covered code, the expected result is a loss of relative coverage.

**Comment by kescobo** [comment]
Yeah, I figured it was something like that. I'm not concerned :-)

**Comment by ChrisRackauckas** [comment]
Coverage improved for Julia, which made coverge reports dropped because it got more accurate 😛

**Pull request merged**
